name: HacktoberShield
description: HacktoberShield Alpha scans incoming PRs for spam content using OpenAI GPT, ensuring a cleaner, safer repo this Hacktoberfest.

inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm init -y &&  npm install @actions/core @actions/github @openai/api
      shell: bash
    - name: Run main script
      run: node index.js
      shell: bash
