name: HacktoberShield
description: HacktoberShield Alpha scans incoming PRs for spam content using OpenAI GPT, ensuring a cleaner, safer repo this Hacktoberfest.

inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'node12'
  main: 'index.js'

jobs:
  hacktoberShieldJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run index.js
        run: node index.js
        env:
          OPENAI_API_KEY: ${{ inputs.openai_api_key }}
          GITHUB_TOKEN: ${{ inputs.github_token }}

  comment:
    needs: hacktoberShieldJob
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Hello**
            🌏
            !
